CREATE TABLE IF NOT EXISTS SNAPSHOT (
    TIME_STAMP INTEGER PRIMARY KEY,
    MEM INTEGER DEFAULT NULL,
    STORAGE INTEGER DEFAULT NULL,
    CPU INTEGER DEFAULT NULL,
    NETWORK INTEGER DEFAULT NULL,
    PROC_COUNT INTEGER DEFAULT NULL,

    FOREIGN KEY (MEM) REFERENCES MEM_SNAP (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (STORAGE) REFERENCES STORAGE_SNAP (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (CPU) REFERENCES CPU_SNAP (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (NETWORK) REFERENCES NETWORK_SNAP (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (PROC_COUNT) REFERENCES PROC_COUNT_SNAP (ID) ON DELETE CASCADE ON UPDATE CASCADE,
);

CREATE TABLE IF NOT EXISTS MEM_SNAP (
    ID INTEGER PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS MEM_SNAP_ENTRY (
    ID INTEGER NOT NULL,
    TOTAL INTEGER  NOT NULL,
    USED INTEGER NOT NULL,
    FREE INTEGER NOT NULL,
    SHARED INTEGER DEFAULT NULL,
    BUFF INTEGER DEFAULT NULL,
    AVAILABLE INTEGER DEFAULT NULL,

    FOREIGN KEY (ID) REFERENCES MEM_SNAP (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS STORAGE_SNAP (
    ID INTEGER PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS STORAGE_SNAP_ENTRY (
    ID INTEGER NOT NULL,
    SYS_NAME TEXT NOT NULL,
    MOUNT TEXT NOT NULL,
    TOTAL_SIZE INTEGER NOT NULL,
    USED INTEGER NOT NULL,
    CAPACITY INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS CPU_SNAP (
    ID INTEGER PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS NETWORK_SNAP (
    ID INTEGER PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS PROC_COUNT_SNAP (
    ID INTEGER PRIMARY KEY

);