[package]
name = "server-man"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common"}
server-lib = { path = "../server-lib" }
serde = {version = "1.0.218", features = ["derive"]}
serde_json = "1.0.139"
rusqlite = { version = "0.33.0", features = ["bundled"] }